### ISSUE TITLE
winkerberos reports version as 0.7.0 but is actually 0.6.0

### ISSUE THREAD

**Issue by scw** [ContinuumIO/anaconda-issues#10001]
### Actual Behavior

Installing `winkerberos` which is labeled as 0.7.0, results in a 0.6.0 installation.

### Expected Behavior
Installed version would match package version.

### Steps to Reproduce

`conda install winkerberos` in a Windows environment. Or, examine the info\recipe\meta.yaml which shows the issue:

```
package:
    name: winkerberos
    version: 0.7.0
source:
    fn: winkerberos-0.6.0.zip
    sha256: a8f81b895092f3e860cb8b8067ab357cf07bb026cb58fad2b32c159ad34dd5f1
    url: https://pypi.org/packages/source/w/winkerberos/winkerberos-0.6.0.zip
```

##### Anaconda or Miniconda version:
Any
##### Operating System:
Windows
