### ISSUE TITLE
libtiff links to unlisted dependencies (xz, zstd) on win

### ISSUE THREAD

**Issue by jschueller** [ContinuumIO/anaconda-issues#10549]
on windows, latest libtiff (win-64/libtiff-4.0.10-h2929a5b_1001.tar.bz2) links to xz, zstd although these are not listed as dependencies:

from meta.yaml.template:
```
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake   # [win]
    - make    # [not win]
  host:
    - zlib
    - jpeg
    - xz  # [not win]
  run:
    - zlib
    - jpeg
    - xz  # [not win]
```

![envlist](https://user-images.githubusercontent.com/3832365/51756541-901b5c80-20c1-11e9-839d-c0bea7bfa79a.png)

![tiffdep](https://user-images.githubusercontent.com/3832365/51756516-7ed25000-20c1-11e9-83e6-6de129868b10.png)
