### ISSUE TITLE
Unable to use anaconda=2021.05 on Github Actions

### ISSUE THREAD

**Issue by mmcky** [ContinuumIO/anaconda-issues#12509]
### Actual Behavior

When trying to install `anaconda=2021.05` using the simple `environment.yml` file 

```yaml
name: quantecon
dependencies:
  - anaconda=2021.05
```

and https://github.com/marketplace/actions/setup-miniconda 

```yaml
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: quantecon
```

The setup fails with numerous `UnsatisfiableError: The following specifications were found to be incompatible with each other:`

### Expected Behavior

Expected to install with no issues as we have been doing with prior releases such as `anaconda=2020.11`

Can replicate using the minimal setup as described above

OR

A project we are trying to upgrade to the latest anaconda for builds

https://github.com/QuantEcon/lecture-python-programming.myst/pull/154/checks?check_run_id=3004812700

##### Anaconda or Miniconda version:

anaconda==2021.05

all prior distributions has worked nicely with github actions environment

Not sure how to give you `github actions` environment info.
