### ISSUE TITLE
Installation failed - MacBook Pro M1 (2020) - macOS Ventura 13.2

### ISSUE THREAD

**Issue by g-r-a-e-m-e** [ContinuumIO/anaconda-issues#13141]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Began having issues opening Spyder from Anaconda in macOS Ventura 13.0.1. Attempted to update using conda, but this failed. Followed macOS uninstall instructions from https://docs.anaconda.com/anaconda/install/uninstall/. Rebooted, downloaded https://repo.anaconda.com/archive/Anaconda3-2022.10-MacOSX-arm64.pkg and attempted install. Installation failed with the following error message: 

"An error occurred during installation. The installation failed." The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

Removed Anaconda files using macOS uninstall instructions from https://docs.anaconda.com/anaconda/install/uninstall/. Rebooted and updated macOS to 13.2. After update completed, rebooted again, re-downloaded https://repo.anaconda.com/archive/Anaconda3-2022.10-MacOSX-arm64.pkg and attempted install. Second installation failed with the same error as above.

*See screenshot below:*

<img width="623" alt="image" src="https://user-images.githubusercontent.com/62527977/218138216-6f235cff-2b4d-4014-955e-7bd2ca450d3f.png">

### Expected behavior or outcome

I expected the installer to successfully complete the Anaconda installation.

**Comment by Cuneoa** [comment]
I experienced the same Anaconda3 installation error. I have the same model Macbook and macOS 13.2. I tried to reinstall because the installer closed before I captured its window. I tried to reinstall but got a message to use 'conda update ...'.

**Comment by Explosion-Scratch** [comment]
Here's how I successfully installed tensorflow with GPU support on my mac M1:

- Remove existing conda
- Find the file with this hash: `0cb5165ca751e827d91a4ae6823bfda24d22c398a0b3b01213e57377a2c54226` → https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-MacOSX-arm64.pkg
- Download the pkg and run it to install conda
- Open terminal, check conda is installed
	- `conda activate`
	- `python --version` → 3.9.12
	- `python`
		- `import platform`
		  `platform.platform()`
	- Check for "arm64"
	- `xcode-select --install`
	- `conda install -y jupyter`
	- `conda deactivate`
	- `conda env create -f tensorflow-apple-metal.yml -n tensorflow`
Where this is the contents of `tensorflow-apple-metal.yml`:

```yml
name: tensorflow
channels:
  - apple
  - conda-forge
dependencies:
    - python=3.10.9
    - pip>=19.0
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - pip:
        - tensorflow-macos
        - tensorflow-metal
        - bayesian-optimization
        - gym
        - kaggle
```
