### ISSUE TITLE
Request for DLT package

### ISSUE THREAD

**Issue by sultaniman** [ContinuumIO/anaconda-issues#13336]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [X] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [ ] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

dlt

### Version

latest

### Platform(s)

linux-64,darwin-64,windows-64

### Location of source code

https://github.com/dlt-hub/dlt/

### Reason for this request

Hey,

I would like to request an package build for [dlt](https://github.com/dlt-hub/dlt/) 
There are 2 good reasons to add dlt to conda and a few weaker ones
* `dlt` provides robust pipelining from dataframes or python generators to strongly typed destinations like Parquet, Bigquery, Snowflake and others, with schema evolution and data contracts, enabling conda users to easily save their outputs for usage by others,
* `dlt` verified [sources](https://github.com/dlt-hub/verified-sources/tree/master/sources) provides a number of business data sources, enabling conda users to use this data for their work,
* easy package management and accesibility for `dlt` dependencies for conda users.

Minor reasons example: data contracts for llm output management: dlt can apply a data contract on top of sources, enabling easier validation of llm outputs, helpers around retryable requests etc

Thanks.

**Comment by sultaniman** [comment]
Using greyskull I generated a recipe for `meta.yml`, as next step I will prepare a PR for staged recipies
```yml
{% set name = "dlt" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlt-{{ version }}.tar.gz
  sha256: 5d6ae7f510084d10c820bc3ca91c1d0708aaf55238d5587ca266583a3f2ea1ae

build:
  entry_points:
    - dlt = dlt.cli._dlt:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.8.1,<3.13
    - requests >=2.26.0
    - pendulum >=2.1.2
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=2.13.0
    - hexbytes >=0.2.2
    - tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - sqlalchemy >=1.4.0
    - typing-extensions >=4.0.0
    - makefun >=1.15.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - astunparse >=1.6.3
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<=3.9.10
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3
    - fsspec >=2022.4.0
    - packaging >=21.1
    - win-precise-time >=1.4.2
  run_constrained:
    - psycopg2-binary >=2.9.1
    - psycopg2cffi >=2.9.0
    - grpcio >=1.50.0
    - google-cloud-bigquery-core >=2.26.0
    - pyarrow >=12.0.0
    - duckdb >=0.6.1,<0.10.0
    - duckdb >=0.10.0,<0.11.0
    - dbt-core >=1.2.0
    - dbt-redshift >=1.2.0
    - dbt-bigquery >=1.2.0
    - dbt-duckdb >=1.2.0
    - dbt-snowflake >=1.2.0
    - dbt-athena-community >=1.2.0
    - s3fs >=2022.4.0
    - gcsfs >=2022.4.0
    - botocore >=1.28
    - snowflake-connector-python >=3.5.0
    - cron-descriptor >=1.2.32
    - pipdeptree >=2.9.0,<2.10
    - pyathena >=2.9.6
    - weaviate-client >=3.22
    - adlfs >=2022.4.0
    - pyodbc >=4.0.39,<5.0.0
    - qdrant-client >=1.6.4,<2.0.0
    - databricks-sql-connector >=2.9.3,<3.0.0
    - dbt-databricks >=1.7.3,<2.0.0

test:
  imports:
    - dlt
  commands:
    - pip check
    - dlt --help
  requires:
    - pip

about:
  home: https://github.com/dlt-hub/dlt
  summary: dlt is an open-source python-first scalable data loading library that does not require any backend to run.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sultaniman
```
