### ISSUE TITLE
Missing icon for app in Launcher 1.0.0 on all platforms

### ISSUE THREAD

**Issue by BjornFJohansson** [ContinuumIO/anaconda-issues#375]
I have specified an icon (see end of the meta.yaml below), but Launcher does not show it.
Can anyone tell me what I am doing wrong? Or did I misunderstand what the "icon" key is for? The icon file is located in the root of the package. The whole meta.yaml is given below for the BjornFJohansson/ypkpathway package:

```
package:
  name: ypkpathway
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  preserve_egg_dir: True
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  entry_points:
    - ypkpathway = ypkpathway.gui:main

source:
  path: .

requirements:

  build:
    - python
    - ipython
    - pyzmq
    - pydna
    - docopt
    - notedown

  run:
    - python
    - ipython
    - pyzmq
    - pydna
    - docopt
    - notedown
    - pyqt

test:
  requires:
    - pyqt
    - nose
  commands:
    #- ypkpathway -h
    #- ypkpathway -v

about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Assemble metabolic pathways from the command line using the ypkpathway protocol

app:
  entry: ypkpathway
  icon: icon.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  type: desk
  own_environment: true
```

Thanks!
