### ISSUE TITLE
rpy2 package is broken on Py3.5, bug has been fixed upstream.

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#759]
_From @fperez on April 18, 2016 22:35_

When loading the IPython magic from rpy2 on python 3.5, the current result is (trimming the traceback):

```
/Users/fperez/usr/conda/lib/python3.5/site-packages/rpy2/robjects/__init__.py in <module>()
     17 
     18 from rpy2.robjects.robject import RObjectMixin, RObject
---> 19 from rpy2.robjects.vectors import (BoolVector,
     20                                    IntVector,
     21                                    FloatVector,

/Users/fperez/usr/conda/lib/python3.5/site-packages/rpy2/robjects/vectors.py in <module>()
    334 
    335 
--> 336 class StrVector(Vector, StrSexpVector):
    337     """      Vector of string elements
    338 

TypeError: type 'rpy2.rinterface.StrSexpVector' is not an acceptable base type
```

This particular bug is [known and already fixed in rpy2 upstream, since version 2.7.4](https://bitbucket.org/rpy2/rpy2/issues/312).  The current version of rpy2 as of Apr 18, 2016 is [2.7.8](https://pypi.python.org/pypi/rpy2). Unfortunately conda still ships the outdated 2.7.0.

_Copied from original issue: conda/conda#2372_

**Comment by ijstokes** [comment]
FWIW, `pip install rpy2` in order to get 2.8.0 (just recently released) results in a different error when I try to `%load_ext rpy2.ipython` in Jupyter (4.2.0):

```
%load_ext rpy2.ipython

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a69f80d0128e> in <module>()
----> 1 get_ipython().magic('load_ext rpy2.ipython')

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(*args,**kwargs)
   2085             return result
   2086 

<decorator-gen-64> in load_ext(self, module_str)

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     64         if not module_str:
     65             raise UsageError('Missing module name.')
---> 66         res = self.shell.extension_manager.load_extension(module_str)
     67 
     68         if res == 'already loaded':

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     82             if module_str not in sys.modules:
     83                 with prepended_to_syspath(self.ipython_extension_dir):
---> 84                     __import__(module_str)
     85             mod = sys.modules[module_str]
     86             if self._call_load_ipython_extension(mod):

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/rpy2/ipython/__init__.py in <module>()
----> 1 from .rmagic import load_ipython_extension

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/rpy2/ipython/rmagic.py in <module>()
     50 # numpy and rpy2 imports
     51 
---> 52 import rpy2.rinterface as ri
     53 import rpy2.robjects as ro
     54 import rpy2.robjects.packages as rpacks

/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/rpy2/rinterface/__init__.py in <module>()
     90 del(os)
     91 
---> 92 from rpy2.rinterface._rinterface import (baseenv,
     93                                          emptyenv,
     94                                          endr,

ImportError: dlopen(/Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-darwin.so, 2): Library not loaded: @rpath/R/lib/libR.dylib
  Referenced from: /Users/ijstokes/anaconda/envs/ana40py35/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-darwin.so
  Reason: image not found

```

**Comment by ijstokes** [comment]
OK, I don't have this problem if I build my own conda package using the `meta.yaml` below, instead of installing via `pip`.  You can find it here: http://anaconda.org/ijstokes/rpy2

```
package:
  name: rpy2
  version: "2.8.0"

source:
  fn: rpy2-2.8.0.tar.gz
  url: https://files.pythonhosted.org/packages/c3/ce/dc91e8879b84771fda231b0a1b46e09615bd072d1d2b135b3ee5913b66c3/rpy2-2.8.0.tar.gz
  md5: cfb51aa4429f81b54afd13dca06b9749
#  patches:
   # List any patch files here
   # - fix.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python
    - r
    - setuptools
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python
    - r
    - setuptools
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six

  run:
    - python
    - r
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six

test:
  # Python imports
  imports:
    - rpy2
    - rpy2.interactive

  run:
    - python
    - r
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six

test:
  # Python imports
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

  commands:
    - echo
    # - python -m rpy2.tests

  requires:
    - ipython
    - r-survival
    - r-ggplot2
    - numpy
    - pandas

about:
  home: http://rpy.sourceforge.net
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python interface to the R language (embedded R)'

```
```
