### ISSUE TITLE
compiler('fortran') cannot find -lquadmath

### ISSUE THREAD

**Issue by speleo3** [ContinuumIO/anaconda-issues#8812]
### Actual Behavior

I assume the following requirement section should be sufficient to build a minimal fortran program:

```yaml
requirements:
  build:
    - {{ compiler('fortran') }}
```

However, this fails because of missing **quadmath** library:

```
/.../conda-bld/fortrantest_1520580612210/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lquadmath
```

More precisely, **libgfortran-ng-7.2.0-h9f7466a_2** is linked to **libquadmath.so.0** and also to **libgcc_s.so.1**, which are available from **libgcc-ng-7.2.0-h7cc24e2_2**. Should **libgcc-ng** be added as a runtime requirement to **libgfortran-ng**?

##### Operating Systems tested:

- Arch Linux (4.14.15-1-ARCH)
- CentOS 6 (2.6.32-642.1.1.el6.x86_64)

##### `conda info` (Arch Linux)
```
     active environment : base
    active env location : /home/thomas/miniconda2
            shell level : 1
       user config file : /home/thomas/.condarc
 populated config files : 
          conda version : 4.4.11
    conda-build version : 3.7.1
         python version : 2.7.13.final.0
       base environment : /home/thomas/miniconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/thomas/miniconda2/pkgs
                          /home/thomas/.conda/pkgs
       envs directories : /home/thomas/miniconda2/envs
                          /home/thomas/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.14.2 CPython/2.7.13 Linux/4.14.15-1-ARCH arch/ glibc/2.26
```

##### Full Example

meta.yaml
```yaml
package:
  name: fortrantest
  version: 1.0
requirements:
  build:
    - {{ compiler('fortran') }}
```

build.sh
```bash
#!/bin/bash
mkdir -p "$PREFIX/bin"
"$FC" -o "$PREFIX/bin/hello" "$RECIPE_DIR/hello.f"
```

hello.f
```fortran
       PRINT *, "Hello World!"
       END
```

**Comment by msarahan** [comment]
Yes, you also need 

```
- {{ compiler('c') }}
```

That's something we need to fix in our recipes.  gfortran depends on gcc, because gcc is where we have the sysroot.  I think gfortran imposes a requirement on libgcc_ng if your package were to compile successfully, but it's wrong that your recipe doesn't get that far.

**Comment by speleo3** [comment]
``{{ compiler('c') }}`` as ``build`` requirement isn't sufficient for me, I still get the same linking errors. But this works:

```yaml
requirements:
  build:
    - {{ compiler('fortran') }}
    - libgcc-ng # [linux] ld: cannot find -lquadmath
    - gcc 4.8   # [osx]   ld: file not found: crtfastmath.o
  host:
    - gcc 4.8   # [osx]   Compiler runtime library in build prefix not found in host prefix
```
