### ISSUE TITLE
conda-build build.sh cannot see directory but its there

### ISSUE THREAD

**Issue by komailrk** [ContinuumIO/anaconda-issues#928]
I am trying to package cpputest and my build.sh cannot see the directory I am trying to cd into. However, that directory does exist. I am not sure if this is a bug or something I am doing incorrectly.

```
bash-4.1$ ls /localdata/miniconds/conda-bld/work/cpputest-3.7dev/
AUTHORS              INSTALL                        README_UsersOfPriorVersions.txt  config.h.in             examples        platforms
CMakeLists.txt       Makefile.am                    aclocal.m4                       config.sub              include         platforms_examples
COPYING              Makefile.in                    autogen.sh                       configure               install-sh      platforms_startup
ChangeLog            Makefile_CppUTestExt           build                            configure.ac            lib             scripts
CppUTest.dsw         Makefile_using_MakefileWorker  builds                           cpputest-hist.txt       ltmain.sh       src
CppUTest.vcproj      NEWS                           cmake                            cpputest.pc.in          m4              tests
CppUTest.vcxproj     README                         compile                          cpputest_build          makeVS2008.bat  valgrind.suppressions
CppUTest_VS2008.sln  README.md                      conda_build.sh                   cpputest_doxy_gen.conf  makeVS2010.bat
CppUTest_VS2010.sln  README_CppUTest_for_C.txt      config.guess                     depcomp                 makeVc6.bat
Doxyfile             README_InstallCppUTest.txt     config.h.cmake                   docs                    missing
```

The build.sh when being executed throws the error:
```
+ cd $'/localdata/miniconds/conda-bld/work/cpputest-3.7dev/cpputest_build\r'
: No such file or directorybld/work/cpputest-3.7dev/conda_build.sh: line 2: cd: /localdata/miniconds/conda-bld/work/cpputest-3.7dev/cpputest_build
Command failed: /bin/bash -x -e /localdata/miniconds/conda-bld/work/cpputest-3.7dev/conda_build.sh
```

build.sh looks like:
```
cd $SRC_DIR/cpputest_build
autoreconf .. -i
../configure
make
```

meta.yml:
```
package:
  name: cpputest
  version: 3.7

source:
  fn: cpputest-3.7dev.tar.gz
  url: https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7dev.tar.gz?raw=true

build:
    number: '1'

requirements:
    build:
        - bzip2
        - zlib 1.2.*
        - autoconf
        - cmake
        - xz 5.2.*
        - automake
        - libtool
    run:
        - autoconf
        - cmake

test:
  commands:
    - cmake --help
```
