### ISSUE TITLE
Making apps for Anaconda-navigator

### ISSUE THREAD

**Issue by melund** [ContinuumIO/anaconda-issues#937]
Hi 

I am trying to figure out how the navigator works. Seems it is still somewhat buggy. 

However, I have a concrete question. I haven't been able to addapt my conda-recipes to set the icon and description for the entries in the Navigtor. See this example where xonsh is missing both the icon and the description. What am I doing wrong. 

![image](https://cloud.githubusercontent.com/assets/1038978/17086947/4bb1f812-51ff-11e6-886e-1687970a6c30.png)

The app section in the recipe looks like this: 
```yaml
app:
  entry: xonsh
  icon: xonsh.png
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  type: desk
```
https://github.com/conda-forge/xonsh-feedstock/blob/master/recipe/meta.yaml
